name: Validate and Publish Dev Container Features

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"

  publish:
    runs-on: ubuntu-latest
    needs: validate
    if: success() && ${{ github.ref == 'refs/heads/main' }}
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
